import type { TTSProvider, GeminiVoiceId, OpenAIVoiceId, VoiceId } from '@/lib/services/tts-service';

export type VoiceGender = 'neutral' | 'masculine' | 'feminine';

export type VoiceIconKey =
  | 'Briefcase'
  | 'GraduationCap'
  | 'Shield'
  | 'Star'
  | 'Book'
  | 'Sparkles'
  | 'Heart'
  | 'Wind'
  | 'Cpu'
  | 'Music'
  | 'Users'
  | 'Cloud'
  | 'Moon'
  | 'Sun'
  | 'Flame'
  | 'Compass'
  | 'Mountain'
  | 'Globe'
  | 'Leaf'
  | 'Waves'
  | 'User';

export interface VoiceMeta {
  id: VoiceId;
  provider: TTSProvider;
  name: string;
  title: string;
  description: string;
  expertise: string[];
  gender: VoiceGender;
  style: string;
  gradient: string;
  iconKey: VoiceIconKey;
}

export const OPENAI_VOICES: VoiceMeta[] = [
  {
    id: 'nova',
    provider: 'openai',
    name: 'Victoria Sterling',
    title: 'Executive Narrator',
    description: 'Polished and professional with excellent pacing.',
    expertise: ['Business', 'Leadership', 'Biography'],
    gender: 'feminine',
    style: 'Warm & Professional',
    gradient: 'from-rose-500 to-pink-600',
    iconKey: 'Briefcase',
  },
  {
    id: 'alloy',
    provider: 'openai',
    name: 'Morgan Blake',
    title: 'Versatile Presenter',
    description: 'Balanced and adaptable, delivering content with clarity.',
    expertise: ['Education', 'Training', 'Corporate'],
    gender: 'neutral',
    style: 'Clear & Articulate',
    gradient: 'from-violet-500 to-purple-600',
    iconKey: 'GraduationCap',
  },
  {
    id: 'ash',
    provider: 'openai',
    name: 'Alexander Grey',
    title: 'Senior Narrator',
    description: 'Deep and resonant voice with gravitas.',
    expertise: ['Drama', 'Thriller', 'Documentary'],
    gender: 'masculine',
    style: 'Deep & Commanding',
    gradient: 'from-stone-500 to-zinc-700',
    iconKey: 'Shield',
  },
  {
    id: 'coral',
    provider: 'openai',
    name: 'Camille Rose',
    title: 'Dynamic Host',
    description: 'Warm and energetic with infectious enthusiasm.',
    expertise: ['Adventure', 'Lifestyle', 'Memoir'],
    gender: 'feminine',
    style: 'Warm & Energetic',
    gradient: 'from-orange-500 to-red-500',
    iconKey: 'Star',
  },
  {
    id: 'echo',
    provider: 'openai',
    name: 'Sebastian Cross',
    title: 'Distinguished Scholar',
    description: 'Refined and contemplative with intellectual depth.',
    expertise: ['Philosophy', 'Academic', 'Documentary'],
    gender: 'masculine',
    style: 'Thoughtful & Measured',
    gradient: 'from-slate-500 to-gray-600',
    iconKey: 'Book',
  },
  {
    id: 'fable',
    provider: 'openai',
    name: 'Aurora Winters',
    title: 'Creative Director',
    description: 'Expressive and dynamic with exceptional range.',
    expertise: ["Fantasy", "Children's", 'Adventure'],
    gender: 'neutral',
    style: 'Dynamic & Expressive',
    gradient: 'from-amber-500 to-orange-600',
    iconKey: 'Sparkles',
  },
  {
    id: 'onyx',
    provider: 'openai',
    name: 'Marcus Ashford',
    title: 'Senior Correspondent',
    description: 'Commanding presence with authoritative delivery.',
    expertise: ['Journalism', 'Mystery', 'History'],
    gender: 'masculine',
    style: 'Authoritative & Bold',
    gradient: 'from-emerald-500 to-teal-600',
    iconKey: 'Shield',
  },
  {
    id: 'sage',
    provider: 'openai',
    name: 'Professor Elena Sage',
    title: 'Knowledge Guide',
    description: 'Patient and wise with natural teaching quality.',
    expertise: ['Education', 'Science', 'How-To'],
    gender: 'feminine',
    style: 'Patient & Wise',
    gradient: 'from-indigo-500 to-purple-600',
    iconKey: 'GraduationCap',
  },
  {
    id: 'shimmer',
    provider: 'openai',
    name: 'Isabella Chen',
    title: 'Wellness Director',
    description: 'Gentle and soothing with calming presence.',
    expertise: ['Wellness', 'Meditation', 'Self-Help'],
    gender: 'feminine',
    style: 'Calming & Intimate',
    gradient: 'from-cyan-500 to-blue-600',
    iconKey: 'Heart',
  },
];

export const GEMINI_VOICES: VoiceMeta[] = [
  // Primary voices
  {
    id: 'Zephyr',
    provider: 'gemini',
    name: 'Zephyr',
    title: 'Conversational Host',
    description: 'Gentle and friendly, perfect for approachable content.',
    expertise: ['Podcast', 'Casual', 'Interview'],
    gender: 'neutral',
    style: 'Friendly & Approachable',
    gradient: 'from-sky-400 to-blue-500',
    iconKey: 'Wind',
  },
  {
    id: 'Puck',
    provider: 'gemini',
    name: 'Puck',
    title: 'Energetic Narrator',
    description: 'Upbeat and enthusiastic, makes learning engaging.',
    expertise: ['Education', 'Entertainment', 'Youth'],
    gender: 'neutral',
    style: 'Upbeat & Energetic',
    gradient: 'from-green-400 to-emerald-500',
    iconKey: 'Sparkles',
  },
  {
    id: 'Charon',
    provider: 'gemini',
    name: 'Charon',
    title: 'Authoritative Voice',
    description: 'Deep and commanding for serious narratives.',
    expertise: ['Documentary', 'Drama', 'News'],
    gender: 'masculine',
    style: 'Deep & Authoritative',
    gradient: 'from-slate-600 to-gray-800',
    iconKey: 'Shield',
  },
  {
    id: 'Kore',
    provider: 'gemini',
    name: 'Kore',
    title: 'Professional Narrator',
    description: 'Balanced and professional with clear delivery.',
    expertise: ['Business', 'Corporate', 'Technical'],
    gender: 'neutral',
    style: 'Balanced & Professional',
    gradient: 'from-blue-500 to-indigo-600',
    iconKey: 'Briefcase',
  },
  {
    id: 'Fenrir',
    provider: 'gemini',
    name: 'Fenrir',
    title: 'Warm Storyteller',
    description: 'Warm and approachable for educational content.',
    expertise: ['Education', 'Audiobooks', 'Tutorials'],
    gender: 'masculine',
    style: 'Warm & Approachable',
    gradient: 'from-orange-500 to-red-600',
    iconKey: 'Book',
  },
  {
    id: 'Leda',
    provider: 'gemini',
    name: 'Leda',
    title: 'Elegant Narrator',
    description: 'Sophisticated voice for literary works.',
    expertise: ['Literature', 'Poetry', 'Art'],
    gender: 'feminine',
    style: 'Elegant & Sophisticated',
    gradient: 'from-purple-500 to-pink-500',
    iconKey: 'Sparkles',
  },
  {
    id: 'Orus',
    provider: 'gemini',
    name: 'Orus',
    title: 'Technical Expert',
    description: 'Clear and articulate for technical content.',
    expertise: ['Technical', 'Science', 'Documentation'],
    gender: 'masculine',
    style: 'Clear & Articulate',
    gradient: 'from-teal-500 to-cyan-600',
    iconKey: 'Cpu',
  },
  {
    id: 'Aoede',
    provider: 'gemini',
    name: 'Aoede',
    title: 'Creative Voice',
    description: 'Expressive and dynamic for creative projects.',
    expertise: ['Creative', 'Art', 'Music'],
    gender: 'feminine',
    style: 'Dynamic & Expressive',
    gradient: 'from-fuchsia-500 to-purple-600',
    iconKey: 'Music',
  },
  // Extended collection
  {
    id: 'Callirrhoe',
    provider: 'gemini',
    name: 'Callirrhoe',
    title: 'Poetic Voice',
    description: 'Flowing grace for poetry and lyrical content.',
    expertise: ['Poetry', 'Lyrical', 'Romance'],
    gender: 'feminine',
    style: 'Graceful & Flowing',
    gradient: 'from-rose-400 to-pink-500',
    iconKey: 'Sparkles',
  },
  {
    id: 'Autonoe',
    provider: 'gemini',
    name: 'Autonoe',
    title: 'Natural Conversationalist',
    description: 'Natural tone for interviews and discussions.',
    expertise: ['Interview', 'Discussion', 'Podcast'],
    gender: 'feminine',
    style: 'Natural & Conversational',
    gradient: 'from-amber-400 to-orange-500',
    iconKey: 'Users',
  },
  {
    id: 'Enceladus',
    provider: 'gemini',
    name: 'Enceladus',
    title: 'Gentle Narrator',
    description: 'Breathy and gentle for intimate storytelling.',
    expertise: ['Meditation', 'ASMR', 'Wellness'],
    gender: 'neutral',
    style: 'Breathy & Gentle',
    gradient: 'from-blue-300 to-indigo-400',
    iconKey: 'Cloud',
  },
  {
    id: 'Iapetus',
    provider: 'gemini',
    name: 'Iapetus',
    title: 'Wise Sage',
    description: 'Wisdom and depth for philosophical content.',
    expertise: ['Philosophy', 'Wisdom', 'Spirituality'],
    gender: 'masculine',
    style: 'Wise & Deep',
    gradient: 'from-indigo-600 to-purple-700',
    iconKey: 'Moon',
  },
  {
    id: 'Umbriel',
    provider: 'gemini',
    name: 'Umbriel',
    title: 'Mysterious Narrator',
    description: 'Atmospheric voice for fantasy and thriller.',
    expertise: ['Fantasy', 'Thriller', 'Mystery'],
    gender: 'neutral',
    style: 'Mysterious & Atmospheric',
    gradient: 'from-violet-600 to-purple-800',
    iconKey: 'Moon',
  },
  {
    id: 'Algieba',
    provider: 'gemini',
    name: 'Algieba',
    title: 'Bright Voice',
    description: "Clear and bright for children's content.",
    expertise: ['Children', 'Education', 'Fun'],
    gender: 'neutral',
    style: 'Bright & Clear',
    gradient: 'from-yellow-400 to-orange-500',
    iconKey: 'Sun',
  },
  {
    id: 'Despina',
    provider: 'gemini',
    name: 'Despina',
    title: 'Cheerful Host',
    description: 'Cheerful energy for lifestyle content.',
    expertise: ['Lifestyle', 'Travel', 'Food'],
    gender: 'feminine',
    style: 'Cheerful & Energetic',
    gradient: 'from-pink-400 to-rose-500',
    iconKey: 'Star',
  },
  {
    id: 'Erinome',
    provider: 'gemini',
    name: 'Erinome',
    title: 'Dramatic Voice',
    description: 'Emotional depth for dramatic readings.',
    expertise: ['Drama', 'Theater', 'Fiction'],
    gender: 'feminine',
    style: 'Dramatic & Emotional',
    gradient: 'from-red-500 to-orange-600',
    iconKey: 'Flame',
  },
  // Stellar voices
  {
    id: 'Algenib',
    provider: 'gemini',
    name: 'Algenib',
    title: 'Science Communicator',
    description: 'Clear voice for scientific content.',
    expertise: ['Science', 'Research', 'Academic'],
    gender: 'masculine',
    style: 'Clear & Informative',
    gradient: 'from-cyan-500 to-blue-600',
    iconKey: 'Compass',
  },
  {
    id: 'Rasalgethi',
    provider: 'gemini',
    name: 'Rasalgethi',
    title: 'Epic Narrator',
    description: 'Commanding presence for epic narratives.',
    expertise: ['Epic', 'History', 'Adventure'],
    gender: 'masculine',
    style: 'Commanding & Epic',
    gradient: 'from-amber-600 to-red-700',
    iconKey: 'Mountain',
  },
  {
    id: 'Laomedeia',
    provider: 'gemini',
    name: 'Laomedeia',
    title: 'Wellness Guide',
    description: 'Soothing voice for wellness content.',
    expertise: ['Wellness', 'Self-Help', 'Health'],
    gender: 'feminine',
    style: 'Soothing & Calming',
    gradient: 'from-teal-400 to-green-500',
    iconKey: 'Heart',
  },
  {
    id: 'Achernar',
    provider: 'gemini',
    name: 'Achernar',
    title: 'Business Voice',
    description: 'Crisp and professional for business.',
    expertise: ['Business', 'Finance', 'Corporate'],
    gender: 'masculine',
    style: 'Crisp & Professional',
    gradient: 'from-blue-600 to-slate-700',
    iconKey: 'Briefcase',
  },
  {
    id: 'Alnilam',
    provider: 'gemini',
    name: 'Alnilam',
    title: 'Motivational Speaker',
    description: 'Strong conviction for motivational content.',
    expertise: ['Motivation', 'Inspiration', 'Leadership'],
    gender: 'masculine',
    style: 'Strong & Convincing',
    gradient: 'from-orange-500 to-red-600',
    iconKey: 'Flame',
  },
  {
    id: 'Schedar',
    provider: 'gemini',
    name: 'Schedar',
    title: 'Family Narrator',
    description: 'Warm and nurturing for family content.',
    expertise: ['Family', 'Parenting', 'Children'],
    gender: 'feminine',
    style: 'Warm & Nurturing',
    gradient: 'from-rose-400 to-pink-500',
    iconKey: 'Heart',
  },
  {
    id: 'Gacrux',
    provider: 'gemini',
    name: 'Gacrux',
    title: 'Technical Instructor',
    description: 'Precision for technical documentation.',
    expertise: ['Technical', 'Tutorial', 'How-To'],
    gender: 'masculine',
    style: 'Precise & Clear',
    gradient: 'from-slate-500 to-gray-600',
    iconKey: 'Cpu',
  },
  {
    id: 'Pulcherrima',
    provider: 'gemini',
    name: 'Pulcherrima',
    title: 'Romance Narrator',
    description: 'Elegant voice for romantic fiction.',
    expertise: ['Romance', 'Literature', 'Drama'],
    gender: 'feminine',
    style: 'Elegant & Romantic',
    gradient: 'from-pink-500 to-rose-600',
    iconKey: 'Heart',
  },
  {
    id: 'Achird',
    provider: 'gemini',
    name: 'Achird',
    title: 'Personal Storyteller',
    description: 'Friendly tone for memoirs and stories.',
    expertise: ['Memoir', 'Personal', 'Storytelling'],
    gender: 'neutral',
    style: 'Friendly & Relatable',
    gradient: 'from-amber-500 to-yellow-600',
    iconKey: 'User',
  },
  {
    id: 'Zubenelgenubi',
    provider: 'gemini',
    name: 'Zubenelgenubi',
    title: 'Unique Voice',
    description: 'Distinctive character for creative projects.',
    expertise: ['Creative', 'Unique', 'Experimental'],
    gender: 'neutral',
    style: 'Distinctive & Unique',
    gradient: 'from-violet-500 to-fuchsia-600',
    iconKey: 'Sparkles',
  },
  {
    id: 'Vindemiatrix',
    provider: 'gemini',
    name: 'Vindemiatrix',
    title: 'Cultural Narrator',
    description: 'Sophisticated voice for cultural content.',
    expertise: ['Culture', 'Art', 'History'],
    gender: 'feminine',
    style: 'Sophisticated & Cultured',
    gradient: 'from-purple-500 to-indigo-600',
    iconKey: 'Globe',
  },
  {
    id: 'Sadachbia',
    provider: 'gemini',
    name: 'Sadachbia',
    title: 'Hopeful Voice',
    description: 'Optimistic tone for inspirational narratives.',
    expertise: ['Inspiration', 'Hope', 'Motivation'],
    gender: 'feminine',
    style: 'Hopeful & Optimistic',
    gradient: 'from-yellow-400 to-amber-500',
    iconKey: 'Sun',
  },
  {
    id: 'Sadaltager',
    provider: 'gemini',
    name: 'Sadaltager',
    title: 'Mindful Narrator',
    description: 'Thoughtful presence for reflective content.',
    expertise: ['Mindfulness', 'Reflection', 'Meditation'],
    gender: 'masculine',
    style: 'Thoughtful & Reflective',
    gradient: 'from-green-500 to-teal-600',
    iconKey: 'Leaf',
  },
  {
    id: 'Sulafat',
    provider: 'gemini',
    name: 'Sulafat',
    title: 'Versatile Voice',
    description: 'Adaptable narration for any genre.',
    expertise: ['Versatile', 'General', 'Adaptable'],
    gender: 'neutral',
    style: 'Versatile & Adaptable',
    gradient: 'from-blue-500 to-cyan-600',
    iconKey: 'Waves',
  },
];

export function getVoices(provider: TTSProvider): VoiceMeta[] {
  return provider === 'gemini' ? GEMINI_VOICES : OPENAI_VOICES;
}

export function getVoiceById(voiceId: VoiceId): VoiceMeta | undefined {
  return [...OPENAI_VOICES, ...GEMINI_VOICES].find(v => v.id === voiceId);
}

export function isVoiceForProvider(voiceId: VoiceId, provider: TTSProvider): boolean {
  if (provider === 'openai') return OPENAI_VOICES.some(v => v.id === (voiceId as OpenAIVoiceId));
  return GEMINI_VOICES.some(v => v.id === (voiceId as GeminiVoiceId));
}

